### PR TITLE
hello-microverse branch

### PR DESCRIPTION
**Pull request by bekjon-me**

### CODE REVIEW

**Comment by KayLemba** [comment]
Hello @bekjon-me  why did you merge this branch you only merge  a branch after your work has been reviewed and  approved.

**Comment by KayLemba** [comment]
Please properly follow instructions in your project requirements. thanks

**Comment by bekjon-me** [comment]
ok i didn;t know, sorry to me

**Review by sja-thedude — COMMENTED** [review]
## Required Changes ♻️

Hi @HtetNaing0814, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

768070f3-bc9a-4aba-b8bc-25793e00ea1e_text

## Highlights
✔️ Good PR title

## Required 
- [ ] Kindly don't merge and delete the branch you are working on until it's approved.
- [ ] Kindly make sure all the linters are setup properly for the project from [here](https://github.com/microverseinc/linters-config/tree/master/html-css)
- [ ] Kindly make sure that you follow the readme template from [here](https://github.com/microverseinc/readme-template).
- [ ] Kindly make sure to add a descriptive description for the pull request.
- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by arslanbisharat** [comment]
Hi Rex Naing, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has been merged and all the changes requested by the previous Code Reviewer are missing. You have also deleted the feature branch. 
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by aimemalaika — COMMENTED** [review]
Hi @HtetNaing0814, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rex-9** [comment]
Thank you for your feedback. But the dashboard still shows Request review.
So I submitted again. Does that happen like that always?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Review by roshan-bajgain — COMMENTED** [review]
Hi @HtetNaing0814, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- GitHub flow is followed. ✔️

## Required Changes ♻️

- [ ]  Linter should be set up correctly for this repository. Linter result should be green. So kindly use [this](https://github.com/microverseinc/linters-config/tree/master/html-css)
- [ ] Add descriptive README file to your project - please use [this template](https://github.com/microverseinc/readme-template) but remember to customize it to your project.
- [ ] There is a .gitignore file listing test.md file and node_modules directory. So that file should not be present in GitHub when it is ignored by git
- [ ] Kindly write a descriptive pull request, what you make changes in the project

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rex-9** [comment]
I have been using "errorlens" and "linter" extensions in my vscode that
shows error in real time. Does it still necessary to include linter file in
my project?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by roshan-bajgain** [comment]
@HtetNaing0814 According to the requirement you need to use HTML and CSS linter and you will be using it through every project So kindly follow the guideline. Thanks

**Review by mukhammadrizooff — COMMENTED** [review]
Hi @HtetNaing0814 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, but you submit invalid PR please send to the submit [this LINK](https://github.com/HtetNaing0814/Hello-World/pull/2/) 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request merged**
